{% set name = "snowflake-sqlalchemy" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51d9d923ebbfefe392582f6e3d0faa83f52e5eb6f190607820e055318dd2d2f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - snowflake-connector-python <3.0.0
    - sqlalchemy >=1.4.0,<2.0.0

test:
  imports:
    - snowflake.sqlalchemy
  requires:
    - pip
  commands:
    - python -m pip check

about:
  home: https://github.com/snowflakedb/snowflake-sqlalchemy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Snowflake SQLAlchemy Dialect

extra:
  recipe-maintainers:
    - xhochy
    - xylar
