{% set name = "snowflake-sqlalchemy" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c598ef37623ef4d035a827f1e84725b3239a47f4366417d089de88f72fc4ac9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - snowflake-connector-python
    - sqlalchemy <2.0.0

test:
  imports:
    - snowflake.sqlalchemy
  requires:
    - pip
  commands:
    - python -m pip check

about:
  home: https://github.com/snowflakedb/snowflake-sqlalchemy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Snowflake SQLAlchemy Dialect

extra:
  recipe-maintainers:
    - xhochy
