{% set name = "snowflake-sqlalchemy" %}
{% set version = "1.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snowflake_sqlalchemy-{{ version }}.tar.gz
  sha256: 942b203de0404b79550c4098ca851aee2b0b22f695426b073e58d71772e38d51

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - sqlalchemy >=1.4.19
    - snowflake-connector-python <5.0.0

test:
  imports:
    - snowflake.sqlalchemy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snowflakedb/snowflake-sqlalchemy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Snowflake SQLAlchemy Dialect
  description: Snowflake SQLAlchemy runs on the top of the Snowflake Connector for Python as a dialect to bridge a Snowflake database and SQLAlchemy applications.
  dev_url: https://github.com/snowflakedb/snowflake-sqlalchemy
  doc_url: https://docs.snowflake.com/developer-guide/python-connector/sqlalchemy

extra:
  recipe-maintainers:
    - xhochy
    - xylar
